# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:13.8.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  
  
  test:
    executor: my-executor
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  
  analyze:
    executor: my-executor
    steps:
      - checkout
      - run: npm audit

workflows:
  react-app-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
  
      
